### ISSUE TITLE
Display sever information

### ISSUE THREAD

**Issue by iqsam** [iquesters/iqwsiot#9]
Display the Software Version number in the footer as a link.

Click the link to display more info about the server side, example:
1. Software Version number
2. PHP Version number
3. MySQL Version number

**Comment by iqsam** [comment]
@nilotpal-saha  your last code was good to go. I made a very minor change.
Task pending now:
views/serverinfo.php
1. include header and footer to the page.

You may then close this issue.

**Comment by nilotpal-saha** [comment]
I'm done with last task that was pending and I'm going close this issue **Display sever information**
